#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


## ---------------------------------------------------
yarn fix-lint ||
(
    echo 'Eslint file fixing failed'
    false 
)
echo "eslint fix success ✅✅✅✅✅✅"


##----------------------------------------------------
yarn check-lint ||
(
    echo 'Eslint check failed'
    false;
)
echo "check eslint styles success ✅✅✅✅✅✅"


##----------------------------------------------------
yarn format ||
(
    echo "Can't format code"
    false;
)
echo "code format success ✅✅✅✅✅✅"


##----------------------------------------------------
yarn check-format ||
(
    echo 'The format is disgusting'
    false;
)
echo "check code format success ✅✅✅✅✅✅"


#If everything passes... try to run build
echo 'Your code looks good ---> trying to build now👍👍👍👍👍👍'
##----------------------------------------------------
yarn build ||
(
    echo 'Your next build failed'
    false;
)
echo "project build successfully 😎😎😎😎😎😎"

